config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  resources 'articles' do
    member do
      post 'purchase'
    end
  end
  resources 'groups' do
    resources 'messages'
  end
  resources 'users', only: [:show] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :purchases, foreign_key: :paid_article_id, dependent: :delete_all
  has_many :buyers, through: :purchases, source: :user
  validates_presence_of [:title, :body]
  mount_uploader :image, ImageUploader
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_talkers, dependent: :delete_all
  has_many :talkers, through: :group_talkers, class_name: 'User'
  has_many :messages, dependent: :delete_all
end

app/models/group_talker.rb
class GroupTalker < ApplicationRecord
  belongs_to :group
  belongs_to :talker, class_name: :User
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :talker, class_name: 'User'
  belongs_to :group
  validates_presence_of :body
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :buyer, class_name: :User
  belongs_to :paid_article, class_name: :Article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles, foreign_key: :author_id, dependent: :delete_all
  has_many :purchases, foreign_key: :buyer_id
  has_many :paid_articles, through: :purchases, source: :article

  has_many :messages, foreign_key: :talker_id, dependent: :delete_all
  has_many :group_talkers, foreign_key: :talker_id
  has_many :groups, through: :group_talkers
  accepts_nested_attributes_for :group_talkers
  mount_uploader :avatar, ImageUploader
  mount_uploader :head_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!, except: [:index, :show]

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :avatar, :note_id, :profile, :head_image])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy, :purchase]

  def index
    @articles = Article.includes(:author).order('created_at DESC')
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.author_id == current_user.id
      @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    if @article.author_id == current_user.id
      @article.destroy
      redirect_to root_path
    end
  end

  def purchase
    Purchase.create(buyer_id: current_user.id, paid_article_id: @article.id)
    Payjp.api_key = Rails.application.secrets.payjp_secret_key
    charge = Payjp::Charge.create(
    amount: @article.price,
    card: params['payjp-token'],
    currency: 'jpy'
    )
    redirect_to article_path(@article)
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :image, :price, :limit).merge(author_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = current_user.groups.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      respond_to do |format|
        # format.html { redirect_to group_messages_path(@group) }
        format.json { @group }
      end
    end
  end

  private
  def group_params
    params.require(:group).permit({ talker_ids: [] })
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  def index
    @message = Message.new
    respond_to do |format|
      format.html { group_messages_path(@group) }
      format.json { @new_messages = @group.messages.where('id > ?', params[:message][:id]) }
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        # format.html { redirect_to group_messages_path(@group) }
        format.json
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :id).merge(talker_id: current_user.id, group_id: params[:group_id])
  end

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.order('created_at DESC')
  end

  def search
    @users = User.where('nickname LIKE(?)', "%#{params[:keyword]}%").or(User.where('email LIKE(?)', "%#{params[:keyword]}%")).where.not(email: current_user.email).order('nickname ASC')
    render json: @users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_nickname(user)
    if user.nickname?
      return user.nickname
    else
      return user.email.sub(/@.+/, "")
    end
  end

  def article_image(article)
    content_tag :a, href: article_path(article) do
      concat (content_tag :img, "", src: article.image) if article.image.url
    end
  end

  def user_avatar(user)
    if user.avatar?
      content_tag :img, "", src: user.avatar
    else
      return image_tag asset_path 'prof.jpg'
    end
  end

  def user_profile(user)
    return simple_format(user.profile) if user.profile?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def delete(article)
    if user_signed_in? && article.author_id == current_user.id
      link_to '削除する', article_path, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }
    end
  end

  def edit(user)
    if user_signed_in? && user.id == current_user.id
      content_tag :div, class: 'note__user__edit' do
        concat (content_tag :a, '編集', href: edit_article_path)
      end
    end
  end

  def article_has_price?(article)
    if article.price
      simple_format(truncate(article.body, length: article.limit))
    else
      simple_format(truncate(article.body, length: 192))
    end
  end

  def display_more?(article)
    link_to 'もっとみる', article_path(article) if article.body.length >= 192 || article.price
  end

  def price(article)
    if article.price
      content_tag :div, class: 'content__article__price' do
        concat(content_tag :span, "#{article.price}円")
      end
    end
  end

  def paid?(article)
    if article.price?
      if user_signed_in?
        if current_user.purchases.where(paid_article_id: article.id).present? || article.author_id == current_user.id
          simple_format(article.body.gsub(/\n/, '<br>'))
        else
          render 'shared/pay-wall', article: article
        end
      else
        render 'shared/pay-wall', article: article
      end
    else
      simple_format(article.body.gsub(/\n/, '<br>'))
    end
  end

  def image_on_paywall?(article)
    if article.image.url
      image_tag article.image
    else
      image_tag asset_path 'pen.jpg'
    end
  end

  def can_purchase?
    if user_signed_in?
      form_tag purchase_article_path, method: :post do
        javascript_include_tag "https://checkout.pay.jp", class: 'payjp-button', data: {key: "#{Rails.application.secrets.payjp_public_key}", text: "購入して続きをみる", submit: {text: '購入する'}}
      end
    else
      content_tag(:div, class: 'not-login') do
        link_to '購入して続きを見る', new_user_session_path, method: :post
      end
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_has?(message)
    truncate(message.last.body, length: 40) if message.present?
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def head_image(user)
    content_tag :img, "", src: user.head_image if user.head_image.url
  end
end

app/views/articles/edit.haml
= render "shared/article-form", article: @article

app/views/articles/index.html.haml
= render 'shared/header'
= render 'shared/main-contents'
= render 'shared/footer'

app/views/articles/new.haml
= render "shared/article-form", article: @article

app/views/articles/show.haml
.note-wrapper
  = render 'shared/header'
  .note
    .note__image
      = article_image(@article)
    .note__user
      .note__user__avatar
        = link_to user_avatar(@article.author), user_path(@article.author)
      .note__user__name
        = link_to user_nickname(@article.author), user_path(@article.author)
      .note__user__time-and-delete
        .time
          = @article.created_at.strftime('%Y/%m/%d %H:%M')
        .delete
          = delete(@article)
      = edit(@article.author)
    .note__article
      .note__article__title
        %h1
          = @article.title
      .note__article__body
        = paid?(@article)
    .note__author
      .user-info__header__profile
        .user-info__header__profile__avatar
          = link_to user_path(@article.author) do
            = user_avatar(@article.author)
        .user-info__header__profile__name
          = link_to user_path(@article.author) do
            = user_nickname(@article.author)
        .user-info__header__profile__introduction
          = user_profile(@article.author)
  = render 'shared/footer'

app/views/groups/index.haml
.chat__modal-window__title
  %h1
    チャットで仕事依頼をする
  %i.fa.fa-pencil-square-o.chat-start
  %p.chat-modal-close
    閉じる
.chat__modal-window__wrapper
  = render partial: "shared/group-list", collection: @groups, as: :group

app/views/groups/new.haml
.chat__modal-window__title
  %p.fa.fa-arrow-left.back
  %h1
    メッセージを作成する
  %p.chat-modal-close
    閉じる
.chat__modal-window__search-user.clearfix
  %h2 メッセージの送信先：
  .chat__modal-window__search-user__partner
  = form_for @group do |f|
    .chat__modal-window__search-user__field
      = text_field_tag :keyword, '', placeholder: 'チャット相手を選んでください', class: 'chat-group-form__input'
    .chat__modal-window__search-user__list
    .chat__modal-window__search-user__result
      = hidden_field_tag 'group[talker_ids][]', current_user.id

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Note
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/index.haml
.chat__modal-window__title
  %p.fa.fa-arrow-left.back
  .chat__modal-window__title__user
    %h1.avatar
      = user_avatar(@group.talkers.where.not(id: current_user.id).first)
    %h1.nickname
      = user_nickname(@group.talkers.where.not(id: current_user.id).first)
  %p.chat-modal-close
    閉じる
.chat__modal-window__main{ data: { id: @group.id } }
  %ul.chat__modal-window__main__contents
    = render partial: 'shared/chat-main', collection: @group.messages, as: :message
  .chat__modal-window__main__form
    = form_for [@group, @message], html: { class: 'chat-form' } do |f|
      = f.text_field :body, class: 'chat-body'
      = button_tag :submit, class: 'chat-submit' do
        %i.fa.fa-paper-plane

app/views/shared/_article-form.haml
.create-note-wrapper
  .create-note
    = form_for article do |f|
      .article__modal-window
        .article__modal-window__title
          %h1
            公開する
        %ul.article__modal-window__price
          %p 販売設定
          %input.free_or_paid{ type: 'radio', name: 'price', value: 'free' }
          %label 無料
          %input.free_or_paid{ type: 'radio', name: 'price', value: 'paid'}
          %label 有料
          .article__modal-window__price__field
            = f.text_field :price
            %span 円
        .article__modal-window__body-limit
          %p.body-length
          %p.body-limit
            公開文字数：
            = f.number_field :limit
            文字
        .article__modal-window__foot
          .modal-close
            キャンセル
          = f.submit '公開', class: 'modal-submit'
      .create-note__header
        = link_to 'note', root_path, class: 'create-note__header__logo'
        .create-note__header__post
          公開設定
      .create-note__main
        = label_tag 'article[image]', '', class: 'create-note__main__image fa-image'
        = f.file_field :image, style: 'display:none'
        = f.text_area :title, class: 'create-note__main__title', placeholder: 'ノートタイトル'
        = f.text_area :body, class: 'create-note__main__body', placeholder: 'ノート本文'

app/views/shared/_article.haml
.content
  .content__user.clearfix
    .content__user__avatar
      = link_to user_path(article.author) do
        = user_avatar(article.author)
    .content__user__name
      = link_to user_nickname(article.author), user_path(article.author)
    .content__user__time
      = link_to article.created_at.strftime('%Y/%m/%d %H:%M'), article_path(article)
  .content__article
    = price(article)
    .content__article__image
      = article_image(article)
    .content__article__title
      = link_to article.title, article_path(article)
    .content__article__body
      = article_has_price?(article)
    .content__article__more
      = display_more?(article)

app/views/shared/_chat-main.haml
%li.message.clearfix{ data:{ id: message.id } }
  .message__avatar
    = user_avatar(message.talker)
  .message__nickname
    = user_nickname(message.talker)
  .message__time
    = message.created_at.strftime('%Y/%m/%d %H:%M')
  .message__body
    = message.body

app/views/shared/_footer.haml
%footer
  .footer
    これは偽物です

app/views/shared/_group-list.haml
.chat__modal-window__groups.clearfix{data: { id: group.id }}
  .chat__modal-window__groups__avatar
    = user_avatar(group.talkers.where.not(id: current_user.id).first)
  .chat__modal-window__groups__right
    .nickname
      = user_nickname(group.talkers.where.not(id: current_user.id).first)
    .message
      = group_has?(group.messages)

app/views/shared/_header.haml
%header
  %nav
    %ul.top-menu
      %li.top-menu__logo
        = link_to root_path do
          = image_tag asset_path 'logo.svg'
      - if user_signed_in?
        .chat-button
          %i.fa.fa-comments-o
        .chat__modal-window
        -# %li.top-menu__search
        -#   %i.fa.fa-search
        -# %li.top-menu__notification
        -#   %i.fa.fa-bell-o
        %li.top-menu__user
          = user_avatar(current_user)
          .arrow
          %ul.hidden-menu
            %li.hidden-menu__mypage
              = link_to user_path(current_user) do
                %p.mypage-nickname
                  = user_nickname(current_user)
                %p.mypage-display
                  マイページを表示
            %li.hidden-menu__account-setting
              = link_to 'アカウント設定', edit_user_registration_path
            %li.hidden-menu__logout
              = link_to 'ログアウト', destroy_user_session_path, method: :delete
        %li.top-menu__post
          = link_to new_article_path do
            %i.fa.fa-pencil-square-o ノートを投稿
      - else
        %li.top-menu__login
          %span
            = link_to "ログイン", new_user_session_path
            %span /
            = link_to "新規登録", new_user_registration_path
        -# %li.top-menu__search
        -#   %i.fa.fa-search

app/views/shared/_main-contents.haml
.contents
  = render partial: "shared/article", collection: @articles
  -# .more
  -#   もっとみる

app/views/shared/_pay-wall.haml
= simple_format(truncate(article.body, length: article.limit).gsub(/\n/, '<br>'))
.pay-wall
  .pay-wall__text
    %p.pay-wall__text__more
      この続きをみるには
    %p.pay-wall__text__length
      = "(残り#{article.body.length - article.limit}文字)"
  - unless user_signed_in?
    .pay-wall__login
      = link_to 'ログイン', new_user_session_path, class: 'link-green'
      または
      = link_to '会員登録', new_user_registration_path, class: 'link-green'
      をしてください。
  .pay-wall__buy
    .pay-wall__buy__text
      .pay-wall__buy__text--border
        %span ノートを購入する
    .pay-wall__buy__area
      .article-detail.clearfix
        .article-detail__image
          = image_on_paywall?(article)
        .article-detail__title
          = article.title
        .article-detail__name
          = user_nickname(article.author)
        .article-detail__price
          = "#{article.price}円"
      .purchase-button
        = can_purchase?

app/views/shared/_user-info.haml
.user-info__header__profile
  .user-info__header__profile__avatar
    = user_avatar(@user)
  .user-info__header__profile__name
    = user_nickname(@user)
  .user-info__header__profile__introduction
    = user_profile(@user)

app/views/users/show.haml
= render 'shared/header'
.user-info
  .user-info__header
    .user-info__header__image
      = head_image(@user)
    = render 'shared/user-info'
.contents
  = render partial: "shared/article", collection: @articles
= render 'shared/footer'